// next-voice-and-facial-recognition/src/app/FacialRecognition.tsx
import { useEffect, useRef } from "react";

export default function FacialRecognition() {
    const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const getUserMedia = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
          videoRef.current.onplay = () => onPlay();
        }
      } catch (err) {
        console.error("Error accessing webcam: ", err);
      }
    };

    getUserMedia();
  }, []);

  // keep on processing the frames from camera
  const onPlay = () => {

  }

  return (
    <div>
      <h1>Facial Recognition Component</h1>
      <div style={{ position: 'relative' }} className="margin">
        <video
          ref={videoRef}
          id="inputVideo"
          autoPlay
          muted
          style={{ width: '100%', height: 'auto' }}
        />
        <canvas id="overlay" />
      </div>
    </div>
  );
}

// angular-voice-and-facial-recognition/src/app/facial-recognition/facial-recognition.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-facial-recognition',
  standalone: true,
  templateUrl: './facial-recognition.component.html',
  styleUrls: ['./facial-recognition.component.css'],
  imports: [CommonModule]
})
export class FacialRecognitionComponent implements AfterViewInit {
  @ViewChild('videoElement') videoElement!: ElementRef<HTMLVideoElement>;

  ngAfterViewInit(): void {
    this.initWebcam();
  }

  async initWebcam() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true });
      if (this.videoElement && this.videoElement.nativeElement) {
        this.videoElement.nativeElement.srcObject = stream;
        this.videoElement.nativeElement.onplay = () => this.onPlay();
      }
    } catch (err) {
      console.error('Error accessing webcam: ', err);
    }
  }

  // keep on processing the frames from camera
  onPlay() {

  }
}
<p>facial-recognition works!</p>
<div>
    <h1>Facial Recognition Component</h1>
    <div style="position: relative" class="margin">
      <video #videoElement id="inputVideo" autoplay muted style="width: 100%; height: auto;"></video>
      <canvas id="overlay"></canvas>
    </div>
</div>
